routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::post('google/webhook', App\Http\Controllers\GoogleWebhookController::class)->name('google.webhook');

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('event', [App\Http\Controllers\EventController::class, 'index'])->name('event.index');

Route::get('google', [App\Http\Controllers\GoogleAccountController::class, 'index'])->name('google.index');
Route::get('google/oauth', [App\Http\Controllers\GoogleAccountController::class, 'store'])->name('google.store');
Route::get('google/callback', [App\Http\Controllers\GoogleAccountController::class, 'store'])->name('google.callback');
Route::delete('google/{googleAccount}', [App\Http\Controllers\GoogleAccountController::class, 'destroy'])->name('google.destroy');

app/Models/Event.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    use HasFactory;
    protected $with = ['calendar'];
    protected $fillable = ['google_id', 'name', 'description', 'allday', 'started_at', 'ended_at'];

    public function calendar()
    {
        return $this->belongsTo(Calendar::class);
    }

    public function getStartedAtAttribute($start)
    {
        return $this->asDateTime($start)->setTimezone($this->calendar->timezone);
    }

    public function getEndedAtAttribute($end)
    {
        return $this->asDateTime($end)->setTimezone($this->calendar->timezone);
    }

    public function getDurationAttribute()
    {
        return $this->started_at->diffForHumans($this->ended_at, true);
    }
}

resources/views/accounts.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <span>Google Accounts</span>
                    <a class="btn btn-primary btn-sm" href="{{ route('google.store') }}">
                        Add account
                    </a>
                </div>

                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        @forelse ($accounts as $account)
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                <span>{{ $account->name }}</span>
                                <form action="{{ route('google.destroy', $account) }}" method="post">
                                    {{ csrf_field() }}
                                    {{ method_field('delete') }}

                                    <button type="submit" class="btn btn-outline-secondary btn-sm">
                                        delete
                                    </button>
                                </form>
                            </li>
                        @empty
                            <li class="list-group-item">
                                No google accounts.
                            </li>
                        @endforelse
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/events.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Events
                </div>

                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        @forelse ($events as $event)
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                <div>
                                    <strong>{{ $event->name }}</strong><br>
                                    <span class="text-muted">
                                        @if ($event->allday)
                                            {{ $event->started_at->format('l jS F Y') }}
                                            (all day)
                                        @else
                                            {{ $event->started_at->format('l jS F Y \a\t H:i') }}
                                            ({{ $event->duration }})
                                        @endif
                                    </span>
                                </div>
                                <span
                                    class="badge badge-pill" 
                                    style="background-color: {{ $event->calendar->color }};"
                                >
                                    {{ $event->calendar->name }}
                                </span>
                            </li>
                        @empty
                            <li class="list-group-item">
                                No events.
                            </li>
                        @endforelse
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection